'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.296
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Projet_Al_Omrane.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1215800286fEkM9vq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1215800286fEkM9vq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1366990618_Login_Manager() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1366990618_Login Manager", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1366992260_tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1366992260_tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1366992260_tick1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1366992260_tick1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1367006511_dialog_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1367006511_dialog-close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1367006511_dialog_close1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1367006511_dialog-close1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1367007187_001_39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1367007187_001_39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368022637_power_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368022637_power_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368022637_power_off1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368022637_power_off1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368041173_user_group_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368041173_user-group-new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368041759_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368041759_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368042487_file_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368042487_file_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368042487_file_add1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368042487_file_add1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368042624_file_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368042624_file_search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368042813_gtk_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368042813_gtk-refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368042946_delete_file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368042946_delete-file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368110654_preferences_desktop_cryptography() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368110654_preferences-desktop-cryptography", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368111692_Remove_Male_User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368111692_Remove-Male-User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368112262_docx_mac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368112262_docx_mac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368112292_client_account_template() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368112292_client_account_template", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368112292_client_account_template1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368112292_client_account_template1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368127483_administrator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368127483_administrator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368129121_administrator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368129121_administrator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368129121_administrator1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368129121_administrator1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369000261_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369000261_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369000376_stock_folder_move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369000376_stock_folder-move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369149826_user_home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369149826_user-home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369230685_archive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369230685_archive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369230878_document_preview_archive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369230878_document-preview-archive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369230878_document_preview_archive1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369230878_document-preview-archive1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369232184_netvibes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369232184_netvibes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369232217_DeleteRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369232217_DeleteRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369232230_Modify() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369232230_Modify", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369232529_new_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369232529_new-24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1370412243_archive_tar_gz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1370412243_archive-tar-gz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1370412451_teacher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1370412451_teacher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1370412747_shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1370412747_shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1370566573_224230_graphics_viewer_document() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1370566573_224230-graphics-viewer-document", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1370568679_go_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1370568679_go-back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1370575587_scanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1370575587_scanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7ecbd3faaed9531e34f7933ee4096274() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7ecbd3faaed9531e34f7933ee4096274", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property al_omrane() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("al_omrane", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alomrane_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alomrane_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grande_icone_historique() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grande-icone_historique", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property omrane() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("omrane", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property service() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("service", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
