'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.296
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("amrani_foundation.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _04_08_2013_11_43_33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("04-08-2013 11-43-33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1366992260_tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1366992260_tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1367006511_dialog_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1367006511_dialog-close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1367006511_dialog_close1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1367006511_dialog-close1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1367007187_001_39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1367007187_001_39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368022637_power_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368022637_power_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368041173_user_group_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368041173_user-group-new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368041759_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368041759_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368042487_file_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368042487_file_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368042813_gtk_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368042813_gtk-refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368110654_preferences_desktop_cryptography() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368110654_preferences-desktop-cryptography", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368111692_Remove_Male_User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368111692_Remove-Male-User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368127483_administrator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368127483_administrator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368127483_administrator1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368127483_administrator1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1368127483_administrator2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1368127483_administrator2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369000261_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369000261_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369149826_user_home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369149826_user-home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369232184_netvibes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369232184_netvibes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369232217_DeleteRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369232217_DeleteRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1369232230_Modify() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1369232230_Modify", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1370412747_shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1370412747_shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1375633333_event_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1375633333_event-search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1375634761_Engineer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1375634761_Engineer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1375635738_List_bullets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1375635738_List_bullets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1375635738_List_bullets1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1375635738_List_bullets1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1375637457_lists() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1375637457_lists", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1375637457_lists1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1375637457_lists1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1375648247_catalog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1375648247_catalog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1376531173_personal_loan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1376531173_personal_loan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1376542362_Print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1376542362_Print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1376542606_system_log_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1376542606_system-log-out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _971303_502965909772813_295088523_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("971303_502965909772813_295088523_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
